### ISSUE TITLE
Hadoop 3.2.0/Spark2.4.4 incompatible?

### ISSUE THREAD

**Issue by mykolasmith** [spark-redshift-community/spark-redshift#45]
I can't get any combination of version to work.

So far I've tried:

* Hadoop 3.2.1/Spark 2.4.4
* Hadoop 3.2.1/Spark 2.4.3
* Hadoop 3.2.0/Spark 2.4.4
* Hadoop 3.2.0/Spark 2.4.3

...and so on.

I am trying with s3a:// and temporary credentials. Here is the error:
```
Exception in thread "main" java.lang.NumberFormatException: For input string: "100M"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.parseLong(Long.java:631)
	at org.apache.hadoop.conf.Configuration.getLong(Configuration.java:1538)
	at org.apache.hadoop.fs.s3a.S3AFileSystem.initialize(S3AFileSystem.java:248)
```

I've tried with and without setting dependencyOverrides to:

```
dependencyOverrides ++= Seq(
    "com.amazonaws" % "aws-java-sdk-bundle" % "1.11.375",
    "com.fasterxml.jackson.core" % "jackson-databind" % "2.9.5"
  ),
```

Any ideas what I'm doing wrong?  According to https://stackoverflow.com/questions/48149929/hive-1-2-metastore-service-doesnt-start-after-configuring-it-to-s3-storage-inst, it's trying to pull in a dependency from pre-Hadoop 2.8.8. Why is that happening?

**Comment by mykolasmith** [comment]
Figured it out... needed to add exclusion rules:

```
  .settings(libraryDependencies ++= Seq(
    "com.amazon.redshift" % "redshift-jdbc42" % "1.2.27.1051" excludeAll (
      ExclusionRule(organization = "org.apache.hadoop"),
      ExclusionRule(organization = "com.amazonaws")
    ),
    "io.github.spark-redshift-community" %% "spark-redshift" % "4.0.0" excludeAll (
      ExclusionRule(organization = "org.apache.hadoop"),
      ExclusionRule(organization = "com.amazonaws")
    )
  ))
```

**Comment by lucagiovagnoli** [comment]
HI @mykolasmith!  Thanks for opening this. I'm curious about this.
I tried upgrading hadoop some time ago but since spark-redshift-community is heavily using the hadoop fs (filesystem) from an older version, it would require a significant code upgrade.

So did you manage to compile and run your app with hadoop 3 by using that configuration?

**Comment by mykolasmith** [comment]
Hey Luca! Yes, I did, after much frustration, getting it running with
Hadoop 3.2.0/Spark 2.4.4. I’ll post my build.sbt and main application file
on Monday.

As an aside, thank you to Yelp and the whole community for breathing life
into this project. Cheers!

**Comment by lucagiovagnoli** [comment]
Hi @mykolasmith, thanks a lot! Your feedback was very appreciated by the entire team.

I'm curious about excluding hadoop from spark-redshift:
```
"io.github.spark-redshift-community" %% "spark-redshift" % "4.0.0" excludeAll (
      ExclusionRule(organization = "org.apache.hadoop"),
      ExclusionRule(organization = "com.amazonaws")
```

spark-redshift is heavily reliant on hadoop FileSystem (eg see [RedshiftWriter](https://github.com/spark-redshift-community/spark-redshift/blob/master/src/main/scala/io/github/spark_redshift_community/spark/redshift/RedshiftWriter.scala#L25))
Last time I tried this, my spark-redshift would not work when including hadoop versions > [2.7.7](https://github.com/spark-redshift-community/spark-redshift/blob/master/build.sbt#L49) 
The problem was that hadoop 3.x API was so different that spark-redshift would require quite a few changes to upgrade to the newer API.

It'd be useful if you could share your experience, I understand you managed to compile, I assume your application is also running correctly without incurring in `ClassNotFoundExceptions` of any sort?

**Comment by mykolasmith** [comment]
Hi @lucagiovagnoli,

Here's an excerpt from our `build.sbt` file:

```scala
lazy val redshiftETL = (project in file("redshift-etl"))
  .settings(baseSettings)
  .settings(scalaVersion := "2.11.12")
  .settings(name := "redshift-etl")
  .settings(version := "0.1-SNAPSHOT")
  .settings(resolvers ++= Seq(
    "jitpack" at "https://jitpack.io",
    "Mulesoft" at "https://repository.mulesoft.org/nexus/content/repositories/public"
  ))
  .settings(libraryDependencies ++= Seq(
    "com.amazon.redshift" % "redshift-jdbc42" % "1.2.27.1051",
    "io.github.spark-redshift-community" %% "spark-redshift" % "4.0.0" excludeAll (
      ExclusionRule(organization = "org.apache.hadoop"),
      ExclusionRule(organization = "com.amazonaws")
    )
  ))
```

The `baseSettings` referred to above includes the following dependencies:

```scala
  libraryDependencies ++= Seq(
    "org.apache.spark" %% "spark-sql" % sparkVersion % "2.4.4",
    "org.apache.hadoop" % "hadoop-aws" % "3.2.0" % "provided",
    "org.apache.hadoop" % "hadoop-common" % "3.2.0" % "provided",
    "org.apache.hadoop" % "hadoop-mapreduce-client-core" % "3.2.0" % "provided",
    "com.fasterxml.jackson.core" % "jackson-databind" % "2.6.7.1"
  ),
  dependencyOverrides ++= Seq(
    "com.fasterxml.jackson.core" % "jackson-databind" % "2.6.7.1"
  ),
```

Usage is as such:

```scala
val jdbcURL = s"jdbc:redshift://$redshiftURL/$redshiftDB?user=$redshiftUser&password=$redshiftPassword"
val df = spark.read
  .format("io.github.spark_redshift_community.spark.redshift")
  .option("url", jdbcURL)
  .option("tempdir", s3TempDir)
  .option("dbtable", redshiftTable)
  .option("temporary_aws_access_key_id", sys.env("AWS_ACCESS_KEY_ID"))
  .option("temporary_aws_secret_access_key", sys.env("AWS_SECRET_ACCESS_KEY"))
  .option("temporary_aws_session_token", sys.env("AWS_SESSION_TOKEN"))
  .load()

df.show
```

I did have to set the following sparkConf:

`.set("spark.hadoop.fs.s3a.aws.credentials.provider", "org.apache.hadoop.fs.s3a.TemporaryAWSCredentialsProvider")`

...in order to avoid an error where the AWS Credentials chain had an issue with mixed credential implementations.

Hopefully I am not forgetting anything, but that is how I got this module to work with Hadoop 3.2.0. Give it a shot and let me know! Reopening issue for now until it's confirmed working for others.

**Comment by lucagiovagnoli** [comment]
Thanks a lot for posting this! We'll try to update the hadoop version in the near future and circle back

**Comment by Sergeant007** [comment]
For poor soles who face the same issue on EMR: **emr-5.30.1** + **Spark 2.4.5** + **JupyterHub 1.1.0**

Any attempt to use _spark-redshift_ library breaks the entire Spark session. For example:
```
%%configure -f
{ 
    "conf": 
     {
         "spark.jars.repositories": "https://s3.amazonaws.com/redshift-maven-repository/release",
         "spark.jars.packages": "io.github.spark-redshift-community:spark-redshift_2.11:4.0.1,com.amazon.redshift:redshift-jdbc41-no-awssdk:1.2.20.1043"
     }
}
```
and then almost any operation (for instance `spark.table("some_table")`) results in following:
> An error was encountered:
'java.lang.NoSuchMethodError: com.amazonaws.util.StringUtils.trim(Ljava/lang/String;)Ljava/lang/String;;'
Traceback (most recent call last):
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/session.py", line 780, in table
    return DataFrame(self._jsparkSession.table(tableName), self._wrapped)
  File "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 69, in deco
    raise AnalysisException(s.split(': ', 1)[1], stackTrace)
pyspark.sql.utils.AnalysisException: 'java.lang.NoSuchMethodError: com.amazonaws.util.StringUtils.trim(Ljava/lang/String;)Ljava/lang/String;;'

A solution is to exclude the mentioned by @mykolasmith dependencies. **Here is a working configuration:**
```
%%configure -f
{ 
    "conf": 
     {
         "spark.jars.repositories": "https://s3.amazonaws.com/redshift-maven-repository/release",
         "spark.jars.packages": "io.github.spark-redshift-community:spark-redshift_2.11:4.0.1,com.amazon.redshift:redshift-jdbc41-no-awssdk:1.2.20.1043",
         "spark.jars.excludes": "org.apache.hadoop:*,com.amazonaws:*"
     }
}
```
Once _org.apache.hadoop_ and _com.amazonaws_ are excluded, Spark commands work without errors.
